lab_1/urls.py
from django.conf.urls import url
from .views import index
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
]

lab_7/urls.py
from django.conf.urls import url
from .views import index, add_friend, validate_npm, delete_friend, friend_list, friend_detail, get_friend_list

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add-friend/$', add_friend, name='add-friend'),
    url(r'^validate-npm/$', validate_npm, name='validate-npm'),
    url(r'^delete-friend/(?P<friend_id>[0-9]+)/$', delete_friend, name='delete-friend'),
    url(r'^friend-list/$', friend_list, name='friend-list'),
    url(r'^friend-detail/(?P<friend_id>[0-9]+)/$', friend_detail, name='friend-detail'),
    url(r'^get-friend-list/$', get_friend_list, name='get-friend-list'),
]

praktikum/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import lab_1.urls as lab_1
import lab_2.urls as lab_2
import lab_3.urls as lab_3
import lab_4.urls as lab_4
import lab_5.urls as lab_5
import lab_6.urls as lab_6
import lab_7.urls as lab_7
import lab_8.urls as lab_8
import lab_9.urls as lab_9
import lab_10.urls as lab_10
import lab_2_addon.urls as lab_2_addon
from lab_1.views import index as index_lab1
from django.views.generic.base import RedirectView


urlpatterns = [
url(r'^admin/', admin.site.urls),
	url(r'^lab-1/', include(lab_1,namespace='lab-1')),
	url(r'^lab-2/', include(lab_2,namespace='lab-2')),
	url(r'^lab-2-addon/', include(lab_2_addon,namespace='lab-2-addon')),
	url(r'^lab-3/', include(lab_3,namespace='lab-3')),
	url(r'^lab-4/', include(lab_4,namespace='lab-4')),
	url(r'^lab-5/', include(lab_5, namespace='lab-5')),
	url(r'^lab-6/', include(lab_6, namespace='lab-6')),
	url(r'^lab-7/', include(lab_7, namespace='lab-7')),
	url(r'^lab-8/', include(lab_8, namespace='lab-8')),
	url(r'^lab-9/', include(lab_9, namespace='lab-9')),
	url(r'^lab-10/', include(lab_10, namespace='lab-10')),
	url(r'^$', RedirectView.as_view(url='/lab-4/', permanent =True), name='index')	
]

lab_7/models.py
from django.db import models

# Create your models here.
class Friend(models.Model):
    friend_name = models.CharField(max_length=400)
    npm = models.CharField(max_length=250, unique=True)
    
    address = models.CharField(max_length=400, null=True)
    postal_code = models.CharField(max_length=400, null=True)
    birth_place = models.CharField(max_length=400, null=True)
    birth_date = models.CharField(max_length=400, null=True)
    
    generation = models.CharField(max_length=400, null=True)
    study_field = models.CharField(max_length=400, null=True)
    study_program = models.CharField(max_length=400, null=True)
    added_at = models.DateField(auto_now_add=True)

lab_7/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.forms.models import model_to_dict
from django.core import serializers

from django.db import IntegrityError
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from .models import Friend
from .api_csui_helper.csui_helper import CSUIhelper
import os
import json

response = {'author' : 'Jeremy Valentino Manik'}
csui_helper = CSUIhelper()

def index(request):
    mahasiswa_list = csui_helper.instance.get_mahasiswa_list()
    friend_list = Friend.objects.all()
    paginator = Paginator(mahasiswa_list, 7)

    page = request.GET.get('page', 1)
    mahasiswa_list = paginator.page(page)

    response = {"mahasiswa_list": mahasiswa_list, "friend_list": friend_list}
    response['author'] = 'Jeremy Valentino Manik'
    html = 'lab_7/lab_7.html'
    return render(request, html, response)

def friend_list(request):
    friend_list = Friend.objects.all()
    response['friend_list'] = friend_list
    html = 'lab_7/daftar_teman.html'
    return render(request, html, response)
    
def get_friend_list(request):
	if request.method == 'GET':
		friend_list = Friend.objects.all()
		data = serializers.serialize('json', friend_list)
		return HttpResponse(data)

@csrf_exempt
def add_friend(request):
    if request.method == 'POST':
        name = request.POST['name']
        npm = request.POST['npm']
        
        try:
            address = request.POST['alamat']
            postal_code = request.POST['kode_pos']
            birth_place = request.POST['kota_lahir']
            birth_date = request.POST['tgl_lahir']
        
            generation = request.POST['angkatan']
            study_field = request.POST['nm_org']
            study_program = request.POST['nm_prg']
            friend = Friend(
                friend_name=name,
                npm=npm,
                
                address=address,
                postal_code=postal_code,
                birth_date=birth_date,
                birth_place=birth_place,
                
                generation=generation,
                study_field=study_field,
                study_program=study_program)
        except:
            friend = Friend(friend_name=name, npm=npm)
        friend.save()
        data = model_to_dict(friend)
        return HttpResponse(data)

@csrf_exempt
def delete_friend(request, friend_id):
    Friend.objects.filter(id=friend_id).delete()
    return HttpResponseRedirect('/lab-7/')

@csrf_exempt
def validate_npm(request):
    npm = request.POST.get('npm', None)
    data = {
        'is_taken': Friend.objects.filter(npm=npm).exists()
    }
    return JsonResponse(data)

def model_to_dict(obj):
    data = serializers.serialize('json', [obj,])
    struct = json.loads(data)
    data = json.dumps(struct[0]["fields"])
    return data
    
def friend_detail(request, friend_id):
    friend = Friend.objects.get(id=friend_id)
    response['friend'] = friend
    html = 'lab_7/friend_detail.html'
    return render(request, html, response)

lab_7/templates/lab_7/daftar_teman.html
{% extends "lab_7/layout/base.html" %}
{% block content %}
<section name="friend-list" class="friend-list">
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-lg-8">
                  <h2> My Friend(s) </h2>
                  <div id="friend-list" class="list-group">
                  </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}
{% block javascript %}
<script>
    
    $( document ).ready(function () {
            $.ajax({
                method: "GET",
                url: '{% url "lab-7:get-friend-list" %}',
                success: function (friend_list) {
                    var list = JSON.parse(friend_list);
                    if(list.length==0) {
                        var html = '<div class="alert alert-danger text-center">\
                            <strong>Oops!</strong> Tidak ada teman\
                            </div>';
                        $("#friend-list").append(html)
                    }
                    else {
                        $.each(list, function(index, friend) {
                            var delete_button = 
                                '<span class="pull-right">'+
                                  '<span class="btn btn-xs btn-default" onClick="deleteFriend('+friend.pk+', friend'+friend.pk+')">'+
                                    'Delete'+
                                  '</span>'+
                                '</span>';
                            var detail_button =
                            '<span class="pull-right">'+
                              '<a class="btn btn-xs btn-default" href="/lab-7/friend-detail/'+friend.pk+'/">'+
                                'Detail'+
                              '</a>'+
                            '</span>';
                            var html = '<div class="list-group-item clearfix" id="friend'+friend.pk+'">'+
                                        friend.fields.friend_name +
                                        ' (' + friend.fields.npm + ')' +delete_button+ detail_button +'</div>';
                            $("#friend-list").append(html)
                        });
                    }
                }
            });
        });



    var deleteFriend = function(friend_id, friend_html_id) {
      deleteUrl = "/lab-7/delete-friend/"+friend_id+"/"
      curr_friend_html_id = '#'+friend_html_id.id
      $.ajax({
          method: "POST",
          url: deleteUrl,
          complete : function () {
            $(curr_friend_html_id).remove();
          },
      });
    }
</script>
{% endblock %}

lab_7/templates/lab_7/friend_detail.html
{% extends "lab_7/layout/base.html" %}

{% block content %}
<section name="friend-list" class="friend-list">
    <div class="container">
        <div class="row">
        	<div class="col-md-8 col-lg-12">
        		<h2>{{ friend.friend_name }} </h2>
        	</div>
            <div class="col-md-8 col-lg-12">
                <table width="100%">
	                <tr>
	                	<td><h4>NPM</h4></td>
	                	<td><h4>{{ friend.npm }}</h4></td>
	                </tr>
                  <tr>
                    <td><h4>Address</h4></td>
                    <td><h4 id="address">{{ friend.address }}</h4></td>
                  </tr>
	                <tr>
	                	<td><h4>Postal Code</h4></td>
	                	<td><h4>{{ friend.postal_code }}</h4></td>
	                </tr>
	                <tr>
	                	<td><h4>Birth Date</h4>
	                	<td><h4>{{ friend.birth_date }}</h4></td>
	                </tr>
                  <tr>
	                	<td><h4>Birth Place</h4>
	                	<td><h4>{{ friend.birth_place }}</h4></td>
	                </tr>
                  
                  
                  <tr>
	                	<td><h4>Start of Study Year</h4>
	                	<td><h4>{{ friend.generation }}</h4></td>
	                </tr>
                  <tr>
	                	<td><h4>Study Field</h4>
	                	<td><h4>{{ friend.study_field }}</h4></td>
	                </tr>
                  <tr>
	                	<td><h4>Study Program</h4>
	                	<td><h4>{{ friend.study_program }}</h4></td>
	                </tr>
            	</table>
            </div>
        </div>
    </div>
    <div class="container">
      <h4>Location On Google Maps</h4>
    	<div id="googleMap" style="width:300px; height:200px; margin: 50px 0"></div>
    </div>
    <div>
    </div>
</section>
{% endblock %}
{% block javascript %}
<script>
    var address = $("#address").text();

    function initMap() {
      var geocoder = new google.maps.Geocoder();
      geocoder.geocode({'address': address}, function(results, status) {
        if (status === google.maps.GeocoderStatus.OK) {
          var propertiPeta = {
            center: results[0].geometry.location,
            zoom: 15,
            mapTypeId: google.maps.MapTypeId.ROADMAP
          };
          var peta = new google.maps.Map(document.getElementById("googleMap"), propertiPeta);
          var marker = new google.maps.Marker({
            map: peta,
            position: results[0].geometry.location
          });
        } else {
          var html = '<div class="alert alert-danger text-center">\
                                Lokasi tidak ditemukan!\
                              </div>';
                  $("#googleMap").append(html)
        }
      });
    }
</script>
{% endblock %}

lab_7/templates/lab_7/lab_7.html
{% extends "lab_7/layout/base.html" %}
{% block content %}
<section name="mahasiswa-list" id="mahasiswa-list">
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-lg-8">
                <h2> Mahasiswa Fasilkom</h2>
                <div class="list-group">
                    {% if mahasiswa_list %}
                        {% for mahasiswa in mahasiswa_list %}
                            <a class="list-group-item clearfix">
                                {{ mahasiswa.nama }} ({{ mahasiswa.npm }})
                                <span class="pull-right">
                        <span class="btn btn-xs btn-default" onClick="addFriend('{{ mahasiswa.nama }}', '{{ mahasiswa.npm }}')">
                            Tambah sebagai teman
                        </span>
                    </span>
                            </a>
                        {% endfor %}
                    {% else %}
                        <div class="alert alert-danger text-center">
                            <strong>Opps!</strong> Tidak ada mahasiswa
                        </div>
                    {% endif %}
                </div>
            </div>
            <div class="col-lg-4">
                <h2> Teman Saya </h2>
                <div class="list-group" id="friend-list">
                    {% if friend_list %}
                        {% for friend in friend_list %}
                            <a class="list-group-item clearfix">
                                {{ friend.friend_name }} ({{ friend.npm }})
                            </a>
                        {% endfor %}
                    {% else %}
                        <div class="alert alert-danger text-center">
                            <strong>Opps!</strong> Tidak ada teman
                        </div>
                    {% endif %}
                </div>
                <form id="add-friend" action="#">
                    {% csrf_token %}
                    <label for="field_npm">npm</label>
                    <input id="field_npm" type="text" name="npm" class="form-control"/>
                    <label for="field_name">name</label>
                    <input id="field_name" type="text" name="name" class="form-control"/>
                    <button type="submit">Tambah</button>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}
{% block javascript %}
<script>
    var addFriend = function(nama, npm) {
        $.ajax({
            method: "POST",
            url: "{% url "lab-7:add-friend" %}",
            data: { name: nama, npm: npm},
            success : function (friend) {
                html = '<a class="list-group-item clearfix">' +
                    friend.friend_name +
                    '</a>';
                $("#friend-list").append(html)
            },
            error : function (error) {
                alert(error.responseText)
            }
        });
    };

    $("#add-friend").on("submit", function () {
       name = $("#field_name").val()
       npm = $("#field_npm").val()
        addFriend(name, npm)
        event.preventDefault();
    });

    $("#field_npm").change(function () {
        console.log( $(this).val() );
        npm = $(this).val();
        $.ajax({
            method: "POST",
            url: '{% url "lab-7:validate-npm" %}',
            data: {
                'npm': npm
            },
            dataType: 'json',
            success: function (data) {
                console.log(data)
                if (data.is_taken) {
                    alert("Mahasiswa dengan npm seperti ini sudah ada");
                }
            }
        });
    });
</script>
{% endblock %}